// src/api/mockData.js

export const mockAlerts = [
  {
    id: "alert-001",
    name: "High CPU on web-prod-01",
    severity: "Sev0",
    resource: "web-prod-01",
    resourceGroup: "rg-production",
    firedAt: "2026-08-04T06:12:00Z",
    acknowledgedAt: null,
    resolvedAt: null,
    status: "New",
    assignedTo: null,
    alertRule: "CPU > 95% for 5 minutes",
  },
  {
    id: "alert-002",
    name: "Memory pressure on api-gateway-02",
    severity: "Sev1",
    resource: "api-gateway-02",
    resourceGroup: "rg-production",
    firedAt: "2026-08-04T07:45:00Z",
    acknowledgedAt: "2026-08-04T07:52:00Z",
    resolvedAt: null,
    status: "Acknowledged",
    assignedTo: "tory.d@company.com",
    alertRule: "Memory > 85% for 10 minutes",
  },
  {
    id: "alert-003",
    name: "Database connection pool exhausted",
    severity: "Sev1",
    resource: "sql-prod-eastus-01",
    resourceGroup: "rg-data",
    firedAt: "2026-08-04T05:30:00Z",
    acknowledgedAt: "2026-08-04T05:38:00Z",
    resolvedAt: "2026-08-04T06:55:00Z",
    status: "Resolved",
    assignedTo: "sara.k@company.com",
    alertRule: "Connection pool > 90% capacity",
  },
  {
    id: "alert-004",
    name: "Storage account latency spike",
    severity: "Sev2",
    resource: "stprodeastus001",
    resourceGroup: "rg-production",
    firedAt: "2026-08-04T08:01:00Z",
    acknowledgedAt: null,
    resolvedAt: null,
    status: "New",
    assignedTo: null,
    alertRule: "Blob latency > 500ms avg over 5 minutes",
  },
  {
    id: "alert-005",
    name: "Function app failure rate elevated",
    severity: "Sev2",
    resource: "func-billing-processor",
    resourceGroup: "rg-billing",
    firedAt: "2026-08-03T22:14:00Z",
    acknowledgedAt: "2026-08-03T22:20:00Z",
    resolvedAt: "2026-08-03T23:45:00Z",
    status: "Resolved",
    assignedTo: "tory.d@company.com",
    alertRule: "Function failure rate > 5% over 10 minutes",
  },
  {
    id: "alert-006",
    name: "VNet peering connectivity loss",
    severity: "Sev0",
    resource: "vnet-prod-eastus",
    resourceGroup: "rg-networking",
    firedAt: "2026-08-04T09:03:00Z",
    acknowledgedAt: "2026-08-04T09:07:00Z",
    resolvedAt: null,
    status: "Acknowledged",
    assignedTo: "tory.d@company.com",
    alertRule: "Peering status != Connected",
  },
  {
    id: "alert-007",
    name: "App Service response time degraded",
    severity: "Sev3",
    resource: "app-portal-prod",
    resourceGroup: "rg-production",
    firedAt: "2026-08-04T08:45:00Z",
    acknowledgedAt: null,
    resolvedAt: null,
    status: "New",
    assignedTo: null,
    alertRule: "P95 response time > 2000ms",
  },
  {
    id: "alert-008",
    name: "Key Vault access denied spike",
    severity: "Sev2",
    resource: "kv-prod-secrets",
    resourceGroup: "rg-security",
    firedAt: "2026-08-03T18:30:00Z",
    acknowledgedAt: "2026-08-03T18:41:00Z",
    resolvedAt: "2026-08-03T19:10:00Z",
    status: "Resolved",
    assignedTo: "sara.k@company.com",
    alertRule: "403 errors > 10 in 5 minutes",
  },
  {
    id: "alert-009",
    name: "AKS node pool CPU throttling",
    severity: "Sev1",
    resource: "aks-prod-cluster",
    resourceGroup: "rg-containers",
    firedAt: "2026-08-04T07:15:00Z",
    acknowledgedAt: "2026-08-04T07:28:00Z",
    resolvedAt: null,
    status: "Acknowledged",
    assignedTo: "tory.d@company.com",
    alertRule: "Node CPU throttling > 40% for 15 minutes",
  },
  {
    id: "alert-010",
    name: "Load balancer health probe failures",
    severity: "Sev3",
    resource: "lb-prod-eastus",
    resourceGroup: "rg-networking",
    firedAt: "2026-08-04T09:30:00Z",
    acknowledgedAt: null,
    resolvedAt: null,
    status: "New",
    assignedTo: null,
    alertRule: "Health probe success rate < 80%",
  },
];

export const mockResources = [
  {
    id: "res-001",
    name: "web-prod-01",
    type: "Virtual Machine",
    resourceGroup: "rg-production",
    health: "Degraded",
  },
  {
    id: "res-002",
    name: "api-gateway-02",
    type: "API Management",
    resourceGroup: "rg-production",
    health: "Degraded",
  },
  {
    id: "res-003",
    name: "sql-prod-eastus-01",
    type: "SQL Database",
    resourceGroup: "rg-data",
    health: "Available",
  },
  {
    id: "res-004",
    name: "stprodeastus001",
    type: "Storage Account",
    resourceGroup: "rg-production",
    health: "Degraded",
  },
  {
    id: "res-005",
    name: "func-billing-processor",
    type: "Function App",
    resourceGroup: "rg-billing",
    health: "Available",
  },
  {
    id: "res-006",
    name: "vnet-prod-eastus",
    type: "Virtual Network",
    resourceGroup: "rg-networking",
    health: "Unavailable",
  },
  {
    id: "res-007",
    name: "app-portal-prod",
    type: "App Service",
    resourceGroup: "rg-production",
    health: "Degraded",
  },
  {
    id: "res-008",
    name: "kv-prod-secrets",
    type: "Key Vault",
    resourceGroup: "rg-security",
    health: "Available",
  },
  {
    id: "res-009",
    name: "aks-prod-cluster",
    type: "Kubernetes Service",
    resourceGroup: "rg-containers",
    health: "Degraded",
  },
  {
    id: "res-010",
    name: "lb-prod-eastus",
    type: "Load Balancer",
    resourceGroup: "rg-networking",
    health: "Degraded",
  },
];

export const mockTimelineData = [
  { date: "Jul 22", fired: 3, resolved: 3 },
  { date: "Jul 23", fired: 5, resolved: 4 },
  { date: "Jul 24", fired: 2, resolved: 2 },
  { date: "Jul 25", fired: 7, resolved: 5 },
  { date: "Jul 26", fired: 4, resolved: 4 },
  { date: "Jul 27", fired: 6, resolved: 6 },
  { date: "Jul 28", fired: 3, resolved: 2 },
  { date: "Jul 29", fired: 8, resolved: 7 },
  { date: "Jul 30", fired: 5, resolved: 5 },
  { date: "Jul 31", fired: 4, resolved: 3 },
  { date: "Aug 01", fired: 6, resolved: 6 },
  { date: "Aug 02", fired: 9, resolved: 7 },
  { date: "Aug 03", fired: 7, resolved: 5 },
  { date: "Aug 04", fired: 6, resolved: 2 },
];
